In [1]:
from sklearn.datasets import make_classification
import torch

In [5]:
# Step 1: Create a synthetic classification dataset using sklearn
X, y = make_classification(
    n_samples=10,       # Number of samples
    n_features=4,       # Number of features
    n_informative=2,    # Number of informative features
    n_redundant=2,      # Number of redundant features
    n_classes=2,        # Number of classes
    random_state=42     # For reproducibility
)

In [6]:
X

array([[-0.92533575, -1.14021544, -0.83879234,  1.69585767],
       [-0.46171143, -0.58723065, -1.97171753,  2.03731034],
       [ 1.44044386,  1.77736657,  1.51157598, -2.79776041],
       [ 1.54711661,  1.89969252,  0.83444483, -2.39981377],
       [ 0.88394335,  1.06833894, -0.97007347, -0.26156038],
       [ 1.42544359,  1.72725924, -1.18582677, -0.71206911],
       [-0.58067464, -0.72063436, -0.96059253,  1.39720576],
       [-0.76281464, -0.9382051 , -0.54304815,  1.284181  ],
       [-1.59731763, -1.96287438, -0.99225135,  2.57793983],
       [-2.38935955, -2.8953973 ,  1.97686236,  1.20190367]])

In [7]:
X.shape

(10, 4)

In [8]:
y

array([0, 0, 1, 1, 1, 1, 0, 1, 0, 0])

In [9]:
y.shape

(10,)

In [10]:
# Convert the data to PyTorch tensors
X = torch.tensor(X, dtype=torch.float32)
y = torch.tensor(y, dtype=torch.long)

In [14]:
print(X.type)
X

<built-in method type of Tensor object at 0x784d4651d900>


tensor([[-0.9253, -1.1402, -0.8388,  1.6959],
        [-0.4617, -0.5872, -1.9717,  2.0373],
        [ 1.4404,  1.7774,  1.5116, -2.7978],
        [ 1.5471,  1.8997,  0.8344, -2.3998],
        [ 0.8839,  1.0683, -0.9701, -0.2616],
        [ 1.4254,  1.7273, -1.1858, -0.7121],
        [-0.5807, -0.7206, -0.9606,  1.3972],
        [-0.7628, -0.9382, -0.5430,  1.2842],
        [-1.5973, -1.9629, -0.9923,  2.5779],
        [-2.3894, -2.8954,  1.9769,  1.2019]])

In [15]:
y

tensor([0, 0, 1, 1, 1, 1, 0, 1, 0, 0])

In [18]:
from torch.utils.data import Dataset,DataLoader

In [31]:
class CustomDataset(Dataset):
  def __init__(self,X,Y):
    self.x=X
    self.y=Y
    # self.num_worker=num_worker

  def __len__(self):
    return len(self.x)
  def __getitem__(self,indx):
    #you can apply any transformation you want on any kin of datasets like for textual it like
    return self.x[indx],self.y[indx]



In [32]:
dataset=CustomDataset(X,y)

In [33]:
len(dataset)

10

In [34]:
dataset[2]

(tensor([ 1.4404,  1.7774,  1.5116, -2.7978]), tensor(1))

In [35]:
dataloader=DataLoader(dataset,batch_size=2,shuffle=True,num_workers=4)

/usr/local/lib/python3.12/dist-packages/torch/utils/data/dataloader.py:627: UserWarning: This DataLoader will create 4 worker processes in total. Our suggested max number of worker in current system is 2, which is smaller than what this DataLoader is going to create. Please be aware that excessive worker creation might get DataLoader running slow or even freeze, lower the worker number to avoid potential slowness/freeze if necessary.
  warnings.warn(


In [39]:
for batch_features,batch_labels in dataloader:
  print(batch_features)
  print(batch_labels)
  print("_"*50)


tensor([[-2.3894, -2.8954,  1.9769,  1.2019],
        [ 1.4254,  1.7273, -1.1858, -0.7121]])
tensor([0, 1])
__________________________________________________
tensor([[-0.4617, -0.5872, -1.9717,  2.0373],
        [-1.5973, -1.9629, -0.9923,  2.5779]])
tensor([0, 0])
__________________________________________________
tensor([[ 1.4404,  1.7774,  1.5116, -2.7978],
        [ 0.8839,  1.0683, -0.9701, -0.2616]])
tensor([1, 1])
__________________________________________________
tensor([[-0.7628, -0.9382, -0.5430,  1.2842],
        [ 1.5471,  1.8997,  0.8344, -2.3998]])
tensor([1, 1])
__________________________________________________
tensor([[-0.9253, -1.1402, -0.8388,  1.6959],
        [-0.5807, -0.7206, -0.9606,  1.3972]])
tensor([0, 0])
__________________________________________________
